-- MySQL Script generated by MySQL Workbench
-- Sat Sep 26 14:16:28 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sky_blue_team
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sky_blue_team
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sky_blue_team` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sky_blue_team` ;

-- -----------------------------------------------------
-- Table `sky_blue_team`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sky_blue_team`.`Users` ;

CREATE TABLE IF NOT EXISTS `sky_blue_team`.`Users` (
  `skyID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  PRIMARY KEY (`skyID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sky_blue_team`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sky_blue_team`.`Customer` ;

CREATE TABLE IF NOT EXISTS `sky_blue_team`.`Customer` (
  `customerID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `addressID` INT NULL COMMENT '',
  `skyCustomerID` INT NULL COMMENT '',
  `surname` VARCHAR(45) NULL COMMENT '',
  `forename` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`customerID`)  COMMENT '',
  INDEX `skyID_idx` (`skyCustomerID` ASC)  COMMENT '',
  CONSTRAINT `skyID`
    FOREIGN KEY (`skyCustomerID`)
    REFERENCES `sky_blue_team`.`Users` (`skyID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sky_blue_team`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sky_blue_team`.`Address` ;

CREATE TABLE IF NOT EXISTS `sky_blue_team`.`Address` (
  `addressID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `addressLine1` VARCHAR(45) NULL COMMENT '',
  `addressLine2` VARCHAR(45) NULL COMMENT '',
  `postcode` VARCHAR(45) NULL COMMENT '',
  `city` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`addressID`)  COMMENT '',
  CONSTRAINT `addressID`
    FOREIGN KEY (`addressID`)
    REFERENCES `sky_blue_team`.`Customer` (`customerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sky_blue_team`.`CustomerLoyalty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sky_blue_team`.`CustomerLoyalty` ;

CREATE TABLE IF NOT EXISTS `sky_blue_team`.`CustomerLoyalty` (
  `loyaltyID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `customerID` INT NOT NULL COMMENT '',
  PRIMARY KEY (`loyaltyID`, `customerID`)  COMMENT '',
  INDEX `customerID_idx` (`customerID` ASC)  COMMENT '',
  CONSTRAINT `customerID`
    FOREIGN KEY (`customerID`)
    REFERENCES `sky_blue_team`.`Customer` (`customerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sky_blue_team`.`LoyaltyPoints`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sky_blue_team`.`LoyaltyPoints` ;

CREATE TABLE IF NOT EXISTS `sky_blue_team`.`LoyaltyPoints` (
  `loyaltyID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `points` VARCHAR(45) NULL COMMENT '',
  `is_percent` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`loyaltyID`)  COMMENT '',
  CONSTRAINT `loyaltyID`
    FOREIGN KEY (`loyaltyID`)
    REFERENCES `sky_blue_team`.`CustomerLoyalty` (`loyaltyID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sky_blue_team`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sky_blue_team`.`Orders` ;

CREATE TABLE IF NOT EXISTS `sky_blue_team`.`Orders` (
  `orderID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `customerID` INT NULL COMMENT '',
  `date` DATE NULL COMMENT '',
  `price` DECIMAL(9,2) NULL COMMENT '',
  `orderStatusID` INT NULL COMMENT '',
  PRIMARY KEY (`orderID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sky_blue_team`.`OrderedItems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sky_blue_team`.`OrderedItems` ;

CREATE TABLE IF NOT EXISTS `sky_blue_team`.`OrderedItems` (
  `orderedItemsID` INT NULL COMMENT '',
  `orderID` INT NULL COMMENT '',
  `stockID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `quantity` INT NULL COMMENT '',
  INDEX `orderID_idx` (`orderedItemsID` ASC)  COMMENT '',
  PRIMARY KEY (`stockID`)  COMMENT '',
  CONSTRAINT `orderID`
    FOREIGN KEY (`orderedItemsID`)
    REFERENCES `sky_blue_team`.`Orders` (`orderID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sky_blue_team`.`Stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sky_blue_team`.`Stock` ;

CREATE TABLE IF NOT EXISTS `sky_blue_team`.`Stock` (
  `stockID` INT NULL COMMENT '',
  `categoryID` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `total_stock` INT NULL COMMENT '',
  `unit_price` DECIMAL(9,2) NULL COMMENT '',
  PRIMARY KEY (`categoryID`)  COMMENT '',
  INDEX `stockID_idx` (`stockID` ASC)  COMMENT '',
  CONSTRAINT `stockID`
    FOREIGN KEY (`stockID`)
    REFERENCES `sky_blue_team`.`OrderedItems` (`stockID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sky_blue_team`.`ItemCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sky_blue_team`.`ItemCategory` ;

CREATE TABLE IF NOT EXISTS `sky_blue_team`.`ItemCategory` (
  `categoryID` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`categoryID`)  COMMENT '',
  CONSTRAINT `categoryID`
    FOREIGN KEY (`categoryID`)
    REFERENCES `sky_blue_team`.`Stock` (`stockID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sky_blue_team`.`OrderStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sky_blue_team`.`OrderStatus` ;

CREATE TABLE IF NOT EXISTS `sky_blue_team`.`OrderStatus` (
  `orderStatusID` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`orderStatusID`)  COMMENT '',
  CONSTRAINT `orderStatusID`
    FOREIGN KEY (`orderStatusID`)
    REFERENCES `sky_blue_team`.`Orders` (`orderID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
